apiVersion: v2
name: tinkerbell-bmc-discovery-controller
description: Discovers BMCs via mDNS and manages Tinkerbell BMC Machine and Hardware resources from their Redfish inventory.
type: application
version: 0.1.1
appVersion: "0.1.1"
home: https://github.com/tinkerbell-community/tinkerbell-bmc-discovery-controller
sources:
  - https://github.com/tinkerbell-community/tinkerbell-bmc-discovery-controller
